/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazEditarLote;

import Controlador.controlador;
import InterfazLote.InterLote;
import ModeloDatos.Campo;
import ModeloDatos.Lote;
import ModeloDatos.TipoSuelo;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mauro
 */
public class EditarLote extends javax.swing.JFrame {
    controlador Controlador = new controlador();
    int ide;
    DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form EditarLote
     */
    public EditarLote() {
        initComponents();
    }

    public EditarLote(controlador control, int numerocampo) {
         ide = numerocampo;
         Controlador = control;
         initComponents();

         
         List<Campo> campos = new ArrayList();
         campos = Controlador.ObtenerTodosLosCampos();
         for(Campo ca: campos){
             if(ca.getNroCampo()==ide){
                
                 
                List <Lote> lista = new ArrayList();
                String [] titulo = new String []  {"Número de lote","Hectareas","Tipo de suelo","Nombre Tipo de Suelo"};
                dtm.setColumnIdentifiers(titulo);
                tabla.setModel(dtm);
                lista=Controlador.ObtenerTodosLosLotes();
                lista.stream().map((obj) -> new String []{Long.toString(obj.getIdLote()),Long.toString(obj.getSuperficie()),Long.toString(obj.getTiposuelo().getIdTipoSuelo()),obj.getTiposuelo().getDescripcion()}).forEachOrdered((lotes) -> {
                dtm.addRow(lotes);});
                 
             }
         }
         if(this.tabla.getSelectedRow()==-1){
            this.botonborrar.setEnabled(false);
            this.botoneditar.setEnabled(false);
            this.botondividir.setEnabled(false);
         }
    }
    
    public void EditarLote(controlador control,int indicetabla){
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        button2 = new java.awt.Button();
        botoneditar = new java.awt.Button();
        botonborrar = new java.awt.Button();
        superficie = new java.awt.TextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botondividir = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel1.setText("EDITAR LOTE");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 11, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Número", "Nombre de campo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 89, 521, 175));

        button2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        button2.setLabel("Atrás");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 42, -1, -1));

        botoneditar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botoneditar.setLabel("Editar superficie");
        botoneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneditarActionPerformed(evt);
            }
        });
        jPanel1.add(botoneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 120, 20));

        botonborrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botonborrar.setLabel("Borrar lote");
        botonborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonborrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 200, 38));

        superficie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                superficieActionPerformed(evt);
            }
        });
        jPanel1.add(superficie, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 159, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Superficie");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 282, 750, 10));

        botondividir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botondividir.setLabel("Dividir lotes");
        botondividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondividirActionPerformed(evt);
            }
        });
        jPanel1.add(botondividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 310, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        InterLote inicio = new InterLote(Controlador);
        inicio.show(true);
        this.show(false);
        inicio.setLocationRelativeTo(null);
    }//GEN-LAST:event_button2ActionPerformed

    private void botoneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneditarActionPerformed
        int indice, IDE;
        indice=tabla.getSelectedRow();
        IDE=Integer.parseInt((String)dtm.getValueAt(indice,0));
        
        System.out.println(ide);
        System.out.println(IDE);
        Campo campobuscado = new Campo();
        campobuscado=Controlador.ObtenerCampo(Long.valueOf(ide));

                for(Lote lotebuscado: campobuscado.getLotes()){
                    if(lotebuscado.getIdLote()==IDE){
                            lotebuscado.setSuperficie(Integer.parseInt(this.superficie.getText()));
                            Controlador.EditarCampo(campobuscado);
                            
                            this.superficie.setText("");
                    }    

                }
    }//GEN-LAST:event_botoneditarActionPerformed

    private void botonborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonborrarActionPerformed

        
        int indice, identi,valordearray;
        indice=tabla.getSelectedRow();
        identi=Integer.parseInt((String)dtm.getValueAt(indice,0));

        Campo buscadocampo = new Campo();
        
        buscadocampo = Controlador.ObtenerCampo(Long.valueOf(ide));
        for(Lote lotebuscado: buscadocampo.getLotes()){
                    if(lotebuscado.getIdLote()==identi){
                        int getIndex=buscadocampo.getLotes().indexOf(lotebuscado);
                          buscadocampo.getLotes().remove(getIndex);
                          Controlador.BorrarLote(lotebuscado);
                          break;
                    }
        }

    }//GEN-LAST:event_botonborrarActionPerformed

    private void superficieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_superficieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_superficieActionPerformed

    private void botondividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondividirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botondividirActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        this.botonborrar.setEnabled(true);
            this.botoneditar.setEnabled(true);
            //this.botondividir.setEnabled(true);
    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarLote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button botonborrar;
    private java.awt.Button botondividir;
    private java.awt.Button botoneditar;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.TextField superficie;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
